### ISSUE TITLE
403 error on some calls

### ISSUE THREAD

**Issue by forme** [emorikawa/linkedin-oauth2#24]
Hi everyone! 
I use this gem to catch user data from LinkedIn. It works well in most cases. However I'm not able to get skills and some next fields. I use a standard developer account at LinkedIn. I've allowed all scopes in OAuth User Agreement. However, I get 403 error like in an example below. 
```
>> api.skills
Faraday::ClientError: the server responded with status 403
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/response/raise_error.rb:13:in `on_complete'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/bundler/gems/linkedin-oauth2-b4b0de9a9dbc/lib/linked_in/raise_error.rb:10:in `on_complete'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:56:in `call'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/request/url_encoded.rb:15:in `call'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/bundler/gems/linkedin-oauth2-b4b0de9a9dbc/lib/linked_in/api_resource.rb:47:in `get'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/bundler/gems/linkedin-oauth2-b4b0de9a9dbc/lib/linked_in/people.rb:106:in `get'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/bundler/gems/linkedin-oauth2-b4b0de9a9dbc/lib/linked_in/people.rb:97:in `skills'
	from (irb):89
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.1/lib/rails/commands/console.rb:90:in `start'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.1/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `block in require'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'
	from /Users/lex/Sites/tj-api/bin/rails:8:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:241:in `load'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:241:in `block in load'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:241:in `load'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/var/rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```
Is it gem thing or something wrong with my LinkedIn account settings?

P.S. Thanks for a good gem!

**Comment by forme** [comment]
It was my fault. Wrong scope setting in mobile client.

**Comment by andrewsmhay** [comment]
Can you elaborate?
